name: Deploy function-a
on:
    push:
        branches:
            - master
        paths:
            - "*"

jobs:
    deploy:
        name: Deploy Functions
        runs-on: ubuntu-latest
        env:
            REGION: asia-northeast1
            ENTRY_POINT: main
            TOPIC: panda_to_ticktick
        steps:
            - uses: actions/checkout@v2
            - uses: google-github-actions/setup-gcloud@master
              with:
                  project_id: dajare-evaluate
                  service_account_email: panda-to-ticktick@dajare-evaluate.iam.gserviceaccount.com
                  service_account_key: ${{ secrets.gcp }}
            - name: Deploy Functions
              run: |
                  gcloud functions deploy panda_to_ticktick --source ./ --region=${REGION} --entry-point ${ENTRY_POINT} --runtime go113 --trigger-topic=${TOPIC}
